site_name: Metal Tutorial
theme:
  name: material
  logo: /images/metal-logo-2.png
  favicon: /images/metal-logo-2.png
  custom_dir: overrides
  features:
    - content.code.copy
  font:
    code: "SF Mono"
  
  palette: 
      
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
      
  - pymdownx.superfences
    

extra_css:
  - stylesheets/extra.css